### ISSUE TITLE
GL_ARB_separate_shader_objects is not required for Vulkan shaders to work

### ISSUE THREAD

**Issue by SaschaWillems** [Overv/VulkanTutorial#112]
In [the shader module chapter](https://github.com/Overv/VulkanTutorial/blob/master/03_Drawing_a_triangle/02_Graphics_pipeline_basics/01_Shader_modules.md#vertex-shader) you state that GL_ARB_separate_shader_objects is required for Vulkan shaders to work without any further reference as to why this is a requirement:

> The GL_ARB_separate_shader_objects extension is required for Vulkan shaders to work.

But contrary to that statement this shader extension is not explicitly required for Vulkan shaders to work, esp. in that sample were you don't even use any cross-stage in or outputs.

As this is causing confusion it may be a good idea to remove that part from the tutorial, and also remove that extensions as a requirement from the shaders.

Also note that you don't need to redeclare the gl_PerVertex output. If you don't explicitly declare it, the glslang reference compiler will automatically add all used outputs for you.

**Comment by Overv** [comment]
Ah, that is good to know. I don't remember why I originally added it, but I could've sworn it was because not having it used to cause `glslangValidator` to fail back when Vulkan was first publicly released.

The same counts for the `gl_PerVertex`, however in that case I *do* remember why it's explicitly there. It used to be the case that if you didn't have it, the validation layers would complain about you using `shaderClipDistance` or `shaderCullDistance` and that the physical device capability for those was not checked.

I will update the tutorial now.

**Comment by voxelv** [comment]
Looks like it's still in the tutorial later in the [Vertex Buffers](https://vulkan-tutorial.com/en/Vertex_buffers/Vertex_input_description) section.

**Comment by Overv** [comment]
Yeah, looks like I didn't remove it properly at all. Fixed.
