### ISSUE TITLE
Creating a logical device causes a segfault

### ISSUE THREAD

**Issue by Tooniis** [Overv/VulkanTutorial#181]
```
if (vkCreateDevice(physicalDevice, &createInfo, nullptr, &device) != VK_SUCCESS) {
    throw std::runtime_error("failed to create logical device!");
}
```
This causes a segmentation fault.

**Comment by Overv** [comment]
I'd prefer tech support issues to be posted in the comments because more people are able to help out there. The GitHub issues are more appropriate for reporting problems with the tutorial itself.

Additionally, if you'd like to have help with this then make sure to include details about your full code and environment (OS / hardware / driver).

**Comment by Tooniis** [comment]
> I'd prefer tech support issues to be posted in the comments because more people are able to help out there. The GitHub issues are more appropriate for reporting problems with the tutorial itself.
> 
> Additionally, if you'd like to have help with this then make sure to include details about your full code and environment (OS / hardware / driver). With just this snippet there's no way to tell what might be wrong on your end.

Which comment section?

**Comment by Overv** [comment]
The Disqus comments under chapters on [the website](https://vulkan-tutorial.com/).

**Comment by Tooniis** [comment]
It didn't load for me before for some reason. I saw it now.
