### ISSUE TITLE
Choosing swapchain present mode

### ISSUE THREAD

**Issue by alexpanter** [Overv/VulkanTutorial#237]
I've been doing some reading concerning what is the appropriate present mode,
and I thought the tutorial should link to this discussion:
https://github.com/LunarG/VulkanSamples/issues/98

It provides some useful insight on whether to prefer FIFO or MAILBOX as default.
E.g. power consumption on mobile devices has been a concern.

**Comment by alexpanter** [comment]
And reading [here](https://developer.samsung.com/sdp/blog/en-us/2019/07/26/vulkan-mobile-best-practice-how-to-configure-your-vulkan-swapchain):

It seems that `VK_PRESENT_MODE_FIFO_KHR` can _also_ be used for triple buffering, which seems contradictory to the descriptions for [picking presentation mode](https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain) for the swap chain.

**Comment by Overv** [comment]
I see now that there are multiple different approaches that are all called triple buffering simply because they use three buffers.

The triple buffering that the tutorial talks about that is only available with MAILBOX is that the GPU is allowed to render multiple frames per vertical sync interval so that the frame being displayed is as "fresh" as possible. That is not the case with the triple buffering described in the Samsung article (nor is any scheme that limits the number of rendered frames to the number of refresh intervals).

It is a good idea to highlight these details, however.
